#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

	case "${DISTRIB_ID}" in
		Ubuntu|Amazon)
			pkg ensure sysutils/syslog-ng
			pkg ensure sysutils/syslog-ng-json
			;;
	esac
}

main "$@"
