#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  case "${DISTRIB_ID}" in
    Darwin) return 0 ;;
  esac

  if ! type -P syslog-ng >/dev/null; then
    return 1
  fi

  return 0
}

main "$@"
